spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQB9jqVD9Chnd1UxPj0SRng5YKOV86do7vCL82iBNqeEUoSQL4NE3og9+rJ/R616+756iSEClaV13TmzGkgxQRF7YqpkaIZ0qQ6601iauG2vrWf+4vjnsDKht8r4FU/N687KB/2N1BKiFzzsuS/neBo7KJkX2RikC6+yNhDfPfbTFxGim1xi6GpWwBype/VWMQ/C7oK6Sev5jmy7rJRKUdPrpiy45OL3XVBk96o6PzeKq6SkjnG49EvUR/SpNVOk+eDOJSk0b8tIaGJpkmKuuJKN8eS6Sm9Amfqu221oEdKjTAqE2g4bRYlK+6soT6Z5Weg5amEz9Y+v/FfbnwSew2AqAck40Q4CthIk0m93wWGODnb+49Zlfqx8Zw05UIjCROE='

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.

token:
  expiration_time: 86400000 # 86400000 하루
  secret: '{cipher}AQA58FtKOOdIa+2mNYdzM8B4rXLLOBNDhK+KOPPmqR38Ry14SeV4FrZsutD409lz9LQcDDhqzATQdXJtM/YhbWL9ko/XVCl8IQSqfFh6862raJGKh1orUOzmXyq90v7PrYP0nedmwYLIZ3y8QgRj2gdFZOn0dc2oJrL3xoL/3BT0FaeOUQblaofI4L2pHBEVQgIn7ZOh1BNYpb0dKRe/4TOYICwg+WLEQzC4Bg133jOgR/8+Q9VFc0ZJfOn+bKmyxiVd4xmdzQAxjOmmmjki04RuQQugEXTUBBl8n9xvukmYq5BMxEwRA+ioV+8L2qHNZYtw18UuSpdJU8epLR8VvV9FUTWbuQCqN8Q8cKBXQ2Ef5C16PgMeWazs3RI01UCZR/HssN3+vQI9wYR5WULnfIDV'